version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: event_management
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
  flyway:
    container_name: flyway
    image: boxfuse/flyway:5.2.4
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    command: -url=jdbc:mysql://mysql:3306/event_management?verifyServerCertificate=false&useSSL=false -schemas=event_management -user=root -password=root -connectRetries=60 migrate
    depends_on:
      - mysql